# Generated by Django 5.1 on 2024-09-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_empleado_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=100, verbose_name='nombre del proveedor')),
                ('cuit_prov', models.IntegerField(blank=True, null=True, verbose_name='cuit del proveedor')),
                ('tipo_prov', models.CharField(blank=True, max_length=100, null=True, verbose_name='tipo de proveedor')),
                ('direcc_prov', models.CharField(max_length=100, verbose_name='direccion del proveedor')),
                ('tel_prov', models.CharField(blank=True, max_length=50, null=True, verbose_name='telefono del proveedor')),
                ('correo_prov', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email del proveedor')),
            ],
        ),
    ]
