# Generated by Django 5.1 on 2024-09-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('apellido_cli', models.CharField(max_length=100, verbose_name='Apellido del cliente')),
                ('cuit_cli', models.IntegerField(verbose_name='cuit-dni del cliente')),
                ('direcc_cli', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion del cliente')),
                ('tel_cli', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono del cliente')),
            ],
        ),
    ]
