# Generated by Django 5.1 on 2024-10-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_empleados_user_alter_empleados_correo_emplead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='id_caja',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='caja'),
        ),
    ]
