# Generated by Django 5.1 on 2024-10-04 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_cajas_id_caja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='id_cliente',
            new_name='id_cli',
        ),
    ]
