# Generated by Django 5.1.1 on 2024-10-08 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_rename_id_cliente_ventas_id_cli'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hs_apertura', models.DateTimeField(verbose_name='Fecha y hora de apertura')),
                ('fecha_hs_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de cierre')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ingreso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ingreso total del día')),
                ('total_egreso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gastos del día')),
                ('cerrado', models.BooleanField(default=False)),
                ('id_emplead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas', to='stock.empleados')),
            ],
        ),
        migrations.AlterField(
            model_name='compras',
            name='id_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='stock.arqueocaja'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='stock.arqueocaja'),
        ),
        migrations.DeleteModel(
            name='Cajas',
        ),
    ]
