# Generated by Django 5.1 on 2024-10-24 22:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_egreso_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=255)),
                ('proceso', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.empleados')),
            ],
        ),
    ]
